version: '3.8'

services:
  api:
    build: .
    image: sambobbarnes/baseapi
    container_name: baseapi
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=dbcontainer
      - DB_USER=root
      - DB_NAME=example
      - DB_PASSWORD=sbdb211898
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mysql/mysql-server:latest
    container_name: baseapidb
    hostname: dbcontainer
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_HOST: '%'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root' # Change This ---------------------------------------
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sbdb211898' # Change This ---------------------------------------
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sbdb211898'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
# Names our volume


volumes:
  my-db:


networks:
  backend:
    name: dbnet