version: "3.8"
services:
  api:
    env_file:
      - .env
    image: sambobbarnes/resume-api:latest
    depends_on:
      - mysql
    ports:
      - "8080:80"
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    
    networks:
      - api

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'ResumeDb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'resumeApi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'resumedb211898'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'resumeroot211898'

volumes:
  db-data:

networks:
  api: