version: "3.8"
services:
  api:
    env_file:
      - .env
    image: sambobbarnes/resume-api:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    
    networks:
      - api

  db:
    image: mysql:8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'ResumeDb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'resumeApi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'resumedb211898'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'resumeroot211898'
    networks: 
      - api
        
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=ResumeDb -user=resumeApi -password=resumedb211898 -connectRetries=60 migrate
    volumes:
      - ./Db/Sql:/flyway/sql
    depends_on:
      - db
    networks:
      - api

volumes:
  db-data:

networks:
  api: