### Start new session
PUT https://localhost:7211/resume/demo/login

### End session
DELETE https://localhost:7211/resume/demo/logout
Cookie: resume-id={{cookies[0]}}

### Get all resumes
GET https://localhost:7211/resume/get-all
Cookie: resume-id={{cookies[0]}}