---
title: Anonymous User Flows
---

flowchart TB
	subgraph FusionAuth
		delete[Delete Anonymous User]
		create[Create Anonymous User]
		create --> jwt[Generate JWT]
	end
	
	subgraph anonLogin[Anonymous Login]
		start[PUT resume/demo/login]
		token[/JWT/]
		start -- Create User --> create
		jwt -- Returns --> token
	end

	anonLogin --> stop[Use normal resume endpoints]

	subgraph Anonymous Logout
		logout[DELETE resume/demo/logout]
		logout --> check[/Check for User/]
		check --> exists{User Exists?}
		exists -- No --> 403[Forbidden]
		exists -- Yes --> isAnon{Is Anonymous?}
		isAnon -- No --> 403
		isAnon -- Yes --> deleteUserData[Delete User Data]
		deleteUserData --> delete
		delete --> 204[No Content]
		
	end