on:
  push:
    tags:
      - '*.*.*'

permissions: write-all

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Split Version Tag
        env:
          VERSION: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=major::$(echo $VERSION | cut -d. -f1)"

      - name: Replace Version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: '**/Startup.cs'
          find: 'v1'
          replace: 'v${{ steps.split.outputs.major }}'

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          docker build -t ghcr.io/barnesdevelopment/resume-api:latest .
          docker build -t ghcr.io/barnesdevelopment/resume-api:${{github.ref_name}} .

      - name: Push
        run: |
          docker push ghcr.io/barnesdevelopment/resume-api:latest
          docker push ghcr.io/barnesdevelopment/resume-api:${{github.ref_name}}
