on:
  push:
    paths:
      - '**/ResumeAPI/**'

permissions: write-all

jobs:
  build-test-api:
    name: Deploy Development API Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          docker build -t ghcr.io/barnesdevelopment/resume-api:test -f ./Api.Dockerfile .

      - name: Push
        run: |
          docker push ghcr.io/barnesdevelopment/resume-api:test
