on:
  pull_request:

jobs:
  angular-tests:
    name: Angular Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./App/resume-builder

      - name: Run tests
        run: npm run test:coverage
        working-directory: ./App/resume-builder

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf ./App/resume-builder/ctrf/ctrf-report.json
        if: always()

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: ./App/resume-builder/coverage

  dotnet-tests:
    name: .NET Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Run tests
        run: dotnet test
        working-directory: ./ResumeAPI

      - name: Publish test results
        if: always()
        uses: bibipkins/dotnet-test-reporter@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Unit Test Results'
          results-path: ./ResumeAPI/UnitTests/results/*.trx
          coverage-threshold: 80
